### PR TITLE
Updated CpuTypes enum

### PR DESCRIPTION
**Pull request by timyhac**
Updated based on https://github.com/libplctag/libplctag/wiki/Tag-String-Attributes

I note that there is no longer a CONTROLOGIX (with only one L) - is this intentional. Does this still need to be supported?

### CODE REVIEW

**Comment by kyle-github** [comment]
Hmm, that's not right.   Here is the actual C code:

```c
if (!str_cmp_i(cpu_type, "compactlogix") || !str_cmp_i(cpu_type, "clgx") || !str_cmp_i(cpu_type, "lgx") ||
               !str_cmp_i(cpu_type, "controllogix") || !str_cmp_i(cpu_type, "contrologix") ||
               !str_cmp_i(cpu_type, "logix")) {
        pdebug(DEBUG_DETAIL,"Found ControlLogix/CompactLogix PLC.");
        return AB_PLC_LGX;
}
```

I will update the API docs.   Wow.  Clearly I need to go through them more carefully.   Two errors in the docs.   Missing "contrologix" and "clgx" was "clogix" in the docs.

**Comment by kyle-github** [comment]
I looked at the commits.  Thanks for all this work!

Are the renaming changes going to break a lot of code?   While I agree that fitting in with the ecosystem's practices is important, perhaps there could be a transition period?   Does C#/.Net have some sort of means for marking things deprecated?  Java has this and it is helpful.

I would argue that changing names is an API change and thus the version should be bumped in such as way to indicate it.   Sorry if this sounds pedantic, but I am concerned that this could cause some breakage.  So, please do not take this as criticism of your hard work on this!

Apart from the version number, LGTM.  I will leave the versioning up to you and Jody.  I am not doing any commits on this repo, so I am just a bystander!

**Comment by jkoplo** [comment]
Yeah, I think this is breaking in terms of API, but per SemVer the 0.x.x
versions are all considered pre-release and not stable so API changes
aren't unexpected. Eventually we'll get 'stable' and cut a 1.0.0 - at least
that's a practice I've followed with internal libraries.

Timyhac, you're killing it. I'm just trying to keep up on the progress
right now.

Jody

**Comment by timyhac** [comment]
Yes that's what I was thinking (breaking changes allowed pre version1).

There is ObsoleteAttribute which could be used - not sure how it works with
modified enums though - İ don't think you can individual members in an
email as obsolete.

**Comment by timyhac** [comment]
@kyle-github - yes, you can mark enum members as Obsolete.

It comes up as a warning during compilation like `warning CS0612: 'CpuTypes.CONTROLOGIX' is obsolete`.

I'll update this Pull Request according to the current CPU types in the API docs.

**Comment by timyhac** [comment]
The other thing I noticed was that for CPU types that have a dash in them, we need to do a conversion when generating the attribute string. Updated the branch with these changes.

**Comment by timyhac** [comment]
What should we do @libplctag/c-sharp-wrapper re: deprecation warnings?

My view is that because we are pre version 1 it is OK to make breaking changes. The changes are reasonably minor in any case.

**Comment by kyle-github** [comment]
If the wrapper has not been released yet, then I am not so worried, but it sounds like people _are_ using it.   At least the questions I have received in the last week makes it sound like there are a couple people using it already.   

Again, it is not up to me as I am not doing any of the coding, but I would probably put in deprecation warnings anyway if it is not a huge pain.

**Comment by jkoplo** [comment]
A couple thoughts:

1. Will we confuse end-users by having several equivalent options? For example, `logix`, `lgx`, `clgx`, `controllogix`, `contrologix` are all equivalent (per Kyle's documentation) - which do I choose for my ControlLogix PLC project? @kyle-github - are these names reserved in case future differences pop up?

2. The CPU types are AB-only, but are required in the Tag constructor. That sort-of makes the wrapper AB-only. I know that's the primary audience and really all the base library supports for now. Do we want to plan for non-AB targets or just build the wrapper around current-state?

**Comment by timyhac** [comment]
@jkoplo - I think I'd prefer to have only one possibility per unique option, have them the most verbose but accurate (i.e. Logix vs lgx) , and have them use proper C# naming conventions (Pascal-case).

Good point about the tag constructor, maybe we should make it an optional parameter.

**Comment by jkoplo** [comment]
Yeah I think a single value would be my preference too (`Logix`). I just don't want to assume that b/c they're listed as equivalent now that they will always be equivalent... That's a question for @kyle-github.

**Comment by kyle-github** [comment]
Currently they are all equivalent and it is the plan to not deviate from that.   I think that having fixed PLC types is fine in C# because they are enum values and not something someone has to type without Intellisense-like support.   I do not feel like I can change the C library at this point to revert the original decision to support multiple names for the PLC types.  In retrospect, that was probably a bad decision :-(

I am working on the Modbus port precisely to help figure out what a non-AB PLC will need so that these interfaces either get focused only on AB or can be done in such a way as to support other PLC types.

**Comment by timyhac** [comment]
@kyle-github I'm in two minds about what we should do here:

1/ I belive a wrapper shouldn't have opinions that differ from the thing being wrapped.
2/ It is confusing to have several options that do the same thing.

The main issue for me is that it isn't possible to simultaneously support C# conventions and be consistent with the C API.
Underscores aren't allowed, which means for example that it wouldn't be possible to support both lgxpccc and lgx_pccc.

---

I've been doing some more reading on C# naming conventions for enums and I was wrong about the plurality. The enum itself should be singular unless it is a bit-field enum. https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces#naming-enumerations.

This means that some of the classes need to be renamed Events -> Event, StatusCodes -> StatusCode, CpuTypes -> CpuType,

**Comment by jkoplo** [comment]
You know I thought the plurality for enum class names seemed odd, but I
just chocked it up to a style thing.

I think we should pick a few of the names and just support them as an enum.
I'm in favor of a wrapper making things simpler/less complicated as long as
the original functionality is preserved. We can comment the enum to note
the equivalence.

**Comment by timyhac** [comment]
@jkoplo - I've updated according to our conversation.

I wasn't sure which synonym should be used so I just picked which one I thought (and some quick googling of AB website on official product names).

**Pull request merged**
