### PR TITLE
#152

### PR DESCRIPTION
**Pull request by timyhac**

### CODE REVIEW

**Comment by timyhac** [comment]
Hi @jkoplo - this fixes #152, the main change is the separation of mapper classes for bool tags vs bool arrays.

This is technically an API breaking change due to renaming of the bool array mapper class - do you think this is a bump in the minor revision number?

**Comment by jkoplo** [comment]
I mean if it's truly an api breaking change then it should be a major rev. That signals that people can't just upgrade and build - they'll have to take some sort of manual intervention.

I'm on mobile, but I'll take a look tomorrow.

**Comment by timyhac** [comment]
I've modified the Pull Request so there is no public API change and it should work for individual bool tags as well as bool arrays.

I think that this doesn't work for BOOL tags within UDTs e.g. `MyCustomUdt.BoolTagWithinUDT`.

**Review by jkoplo — APPROVED** [review]
So in the end we've got:

1. Change the bool mapper to use Get/SetUint8 instead of Bit
2. Removing some redundant interface callouts

Looks good to me.

**Comment by timyhac** [comment]
Thanks @jkoplo!

The only issue I see now is that I think this means bool tags on UDTs stop working.

I don't have a PLC available to confirm this though.

Possibly better to keep BoolMapper as-is and add a new one for individual bool tags?

What do you think?

**Pull request merged**
