### PR TITLE
Fix for #304 - use `plc_tag_create_ex` for Initialization

### PR DESCRIPTION
**Pull request by timyhac**
This PR modifies the `Initialize`/`InitializeAsync` methods to make use of `plc_tag_create_ex` instead of `plc_tag_create` - which allows us to capture events early in the tag lifecycle.

### CODE REVIEW

**Review by jkoplo — APPROVED** [review]
The only thing that I'm unsure of is if moving `SetUpEvents()` earlier in the methods results in a different sequence and potentially an issue in a corner case? I just looked at the GH review so I don't have the full codebase in front of me right now.

Good enough for an alpha release at least...

**Comment by kyle-github** [comment]
Over the holiday weekend (here in the US), I'll do some testing to make sure that the Modbus code is actually generating the right events.   That will tackle this problem from the other end.

**Comment by jkoplo** [comment]
@kyle-github do you have a good modbus simulator or even some automated tests for modbus?

**Comment by kyle-github** [comment]
In the src/tests/ directory I have a couple files that do testing.   One is a small wrapper (in Python) around libmodbus which is a C-based library that is very, very widely used for Modbus on Linux.   This sets up a small Modbus server with some registers.  The other is run_tests.sh which is just a shell script that runs 20+ specific tests against my real hardware and this Modbus simulator and against my CIP simulator.   The CI system runs a subset of these since there is no PLC hardware in GitHub's test runner pool.

That said, I don't have the ability to inject delays or faults into the Modbus tests like I do with the CIP tests (delays are supported and used to test timeouts).

**Pull request merged**
