### PR TITLE
Consolidated exception types

### PR DESCRIPTION
**Pull request by timyhac**

### CODE REVIEW

**Comment by timyhac** [comment]
A few things we could consider are:
* Making the `ThrowIfError()` function a utility that wrapper consumers could call (not just from within the Tag class).
* Making the error descriptions more descriptive, could use the [API documentation](https://github.com/libplctag/libplctag/wiki/API#status-codes) to determine the description text.

**Comment by timyhac** [comment]
The other option is to remove this function entirely and provide another constructor for LibPlcTagException that takes a StatusCode and maybe that is self documenting enough.
The library consumer could do
```csharp
if(myTag.GetStatus() != StatusCodes.StatusOk)
    throw new LibPlcTagException(myTag.GetStatus()))
```

**Comment by kyle-github** [comment]
I like the simplicity of that, @timyhac !

From now on any addition to my error codes should be considered an API change.   I'll need you to help keep me honest here!   I do not change error codes very often, but since they are becoming enums elsewhere (I did not use enums to allow support on older compilers and some less common systems), they are part of the published API.

I should send this as a note to the rest of the maintainers...

**Comment by jkoplo** [comment]
I like doing it in the exception constructor - that feels clean. I'll review/merge PRs later tonight.

**Comment by timyhac** [comment]
Thanks - I'll update this PR once we've merged in the other changes (to do with Enums).

**Pull request merged**
