### PR TITLE
Issue 178 : Boolean readings do not work with C#

### PR DESCRIPTION
**Pull request by corentingallet**
Always returns False.
Issue : https://github.com/libplctag/libplctag.NET/issues/178

### CODE REVIEW

**Comment by timyhac** [comment]
Is this just a code simplification, or have you found a situation where it isn't returning the expected result?

As you can appreciate, the mapping between PLC data representations and their interpretations is complex, so it would be useful if you could share what you've discovered.

**Comment by timyhac** [comment]
Hi @corentingallet - did you have any comments on the [above](https://github.com/libplctag/libplctag.NET/pull/335#issuecomment-1498386942)?

**Comment by corentingallet** [comment]
Hello,
Yes, I will answer soon. We're still testing the code on different devices.

**Comment by timyhac** [comment]
Hi @corentingallet - did you have any comments on the above?

**Comment by corentingallet** [comment]
I tested it (with success) on an Allen Bradley / Rockwell PLC (Logix5561 ; compact Logix) and an Omron (but I don't remember the exact type). I'm still trying to find other real examples.

**Pull request merged**
