### PR TITLE
Updated Enums

### PR DESCRIPTION
**Pull request by timyhac**
* Added DebugLevels enum
* Added Events enum
* Renamed StatusCode to StatusCodes
* Naming convention for C# enums uses Pascal case - updated StatusCode

### CODE REVIEW

**Comment by jkoplo** [comment]
I reviewed these changes. In general, I like having everything as an enum but it does put a little more burden on keeping the wrapper up to date with the values in the base library. I think it's a worthwhile tradeoff though.

I did notice that two new status values were added to the enum and there weren't associated exceptions and they weren't handled in the case structure in Tag that throws exceptions from status value. I fixed that and committed to this branch.

I'd be in favor of trimming down the exception classes to only a few and providing more details in the message. This seems more consistent with how .net itself does things.

**Comment by timyhac** [comment]
@jkoplo - what if we just had a single Exception type `LibPlcTagException`?

**Comment by jkoplo** [comment]
That's probably just fine and would simplify things a lot. I could maybe see an argument for a separate exception for overall connection issues vs specific tag issues since you might want to handle them differently, but that's about it.

**Comment by timyhac** [comment]
Hi @jkoplo - I've updated the branch with latest changes, so now it can be merged.

I'll create a new branch containing the change for the Exception types.

**Comment by timyhac** [comment]
Hi @jkoplo - see PR https://github.com/libplctag/libplctag.NET/pull/34 for a basic implementation of consolidated exception types.

**Comment by timyhac** [comment]
Hi @jkoplo - I've updated this branch also.

I will make a separate branch to rename CpuTypes to CpuType and Events to Event but won't do so until this has been merged.

**Pull request merged**
